### ISSUE TITLE
使用docker-compose部署后无法访问

### ISSUE THREAD

**Issue by Dnine7** [nashaofu/wol#12]
使用docker-compose部署后无法访问

docker-compose.yml
```
version: '3'
services:
  wol:
    image: ghcr.io/nashaofu/wol:latest
    container_name: wol
    ports:
      - "3300:3300"
    volumes:
      - /home/dnine7/wol.yaml:/opt/wol/wol.yaml
    restart: always

```
部署后访问localhost:3300,无法访问
进入容器内部使用curl localhost:3300  
```
/opt/wol # curl 127.0.0.1:3300
curl: (52) Empty reply from server
```
